/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ocams.felix;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import com.ocams.OCAMS;
import javax.swing.JOptionPane;
/**
 *
 * @author Gp62
 */
public class DetailStock extends javax.swing.JFrame {
    DefaultComboBoxModel<String> cb;
    DefaultTableModel table;
    public HeaderStock parent;
    /**
     * Creates new form framestock
     */
    public DetailStock() {
        initComponents();
        lblTrans.setText(OCAMS.SQL.transID());
        cb = new DefaultComboBoxModel<>();
        ArrayList<String[]> data = OCAMS.SQL.executeQueryGetArray("SELECT nama_bahan from bahan");
        for(String[] d: data){
            cb.addElement(d[0]);
        }
        cbNama.setModel(cb);
        String header[] = {"ID Bahan","Nama Bahan","Jumlah","Tersisa","Harga Total"};
        table = new DefaultTableModel(null, header){
            // http://stackoverflow.com/questions/1990817/how-to-make-a-jtable-non-editable
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        GView.setModel(table);
        lblSatuan.setText(OCAMS.SQL
            .executeGetScalar(
                "SELECT satuan from bahan where nama_bahan = '"+cb.getSelectedItem().toString()+"'"));
        
    }
    
    public DetailStock(String kode){
        initComponents();
        lblTrans.setText(kode);
        cb = new DefaultComboBoxModel<>();
        ArrayList<String[]> data = OCAMS.SQL.executeQueryGetArray("SELECT nama_bahan from detail_stock");
        for(String[] d: data){
            cb.addElement(d[0]);
        }
        cbNama.setModel(cb);
        String header[] = {"ID Bahan","Nama Bahan","Jumlah","Tersisa","Harga Total"};
        table = new DefaultTableModel(null, header){
            // http://stackoverflow.com/questions/1990817/how-to-make-a-jtable-non-editable
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        GView.setModel(table);
        ArrayList<String[]> temp = OCAMS.SQL.executeQueryGetArray(
                "SELECT d.`ID_Bahan`,b.`Nama_Bahan`, d.`Jumlah`, (d.`Jumlah` - d.`Keluar`) as sisa, d.`Harga`\n" +
                "FROM detail_stock d, bahan b\n" +
                "WHERE d.ID_Bahan = b.ID_Bahan");
        //Tambahkan Data
        for(String[] d: temp){
            table.addRow(d);
        }
        lblSatuan.setText(OCAMS.SQL
            .executeGetScalar(
                "SELECT satuan from bahan where nama_bahan = '"+cb.getSelectedItem().toString()+"'"));
        
        updateTotal();
    }
    
    public void updateTotal(){
        int total = 0;
        for (int i = 0; i < table.getRowCount(); i++) {
            int temp = Integer.parseInt(table.getValueAt(i, 4).toString());
            total += temp;
        }
        lblTotal.setText(String.valueOf(total));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTrans = new javax.swing.JLabel();
        txtHargaBeli = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spJumlah = new javax.swing.JSpinner();
        cbNama = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        GView = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblSatuan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbKas = new javax.swing.JRadioButton();
        cbHutang = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTrans.setText("000");

        jButton1.setText("Tambahkan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Barang  :");

        jLabel3.setText("Jumlah            :");

        jLabel4.setText("ID Transaksi   :");

        jLabel5.setText("Harga Beli       :");

        cbNama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbNamaFocusLost(evt);
            }
        });

        GView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(GView);

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblSatuan.setText("Satuan");

        jLabel1.setText("Total Pembelian");

        lblTotal.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Pembayaran");

        buttonGroup1.add(cbKas);
        cbKas.setSelected(true);
        cbKas.setText("Kas");

        buttonGroup1.add(cbHutang);
        cbHutang.setText("Hutang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spJumlah)
                            .addComponent(txtHargaBeli)
                            .addComponent(cbNama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSatuan))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbKas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbHutang)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblTrans))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(spJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSatuan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(155, 155, 155)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblTotal))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbKas)
                            .addComponent(cbHutang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean cek = true;
        String kode = OCAMS.SQL.executeGetScalar("SELECT id_bahan FROM bahan where nama_bahan = '"
                +cbNama.getSelectedItem().toString()+"'");
        String tambah[] = {kode,cbNama.getSelectedItem().toString(),spJumlah.getValue().toString()
                ,"0",txtHargaBeli.getText()};
        for (int i = 0; i < table.getRowCount(); i++) {
            if(table.getValueAt(i, 0).toString().equalsIgnoreCase(kode)){
                int t = Integer.parseInt(table.getValueAt(i, 2).toString());
                t += Integer.parseInt(spJumlah.getValue().toString());
                //"ID Bahan","Nama Bahan","Jumlah","Tersisa","Harga Total"
                table.setValueAt(t, i,2);
                t = Integer.parseInt(table.getValueAt(i, 4).toString());
                t+= Integer.parseInt(txtHargaBeli.getText());
                table.setValueAt(t, i,4);
                cek = false;
            }
        }
        if(cek) table.addRow(tambah);
        updateTotal();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        OCAMS.SQL.executeNonQuery("INSERT INTO HEADER_STOCK VALUES('"+lblTrans.getText()
                +"',CURRENT_DATE,'"+OCAMS.userYangLogin.getKdUser()+"') "
                + "on duplicate key update id_trans = id_trans");
        for (int i = 0; i < table.getRowCount(); i++) {
            OCAMS.SQL.executeNonQuery("INSERT INTO detail_stock values('"+lblTrans.getText()+"',"
                + "'"+table.getValueAt(i, 0)+"',"+spJumlah.getValue().toString()+","
                +txtHargaBeli.getText()+",0) "
                    + "on duplicate key update harga = harga"
                    + "");
        }
        String perkiraan[];
        if(cbKas.isSelected()){
            perkiraan = new String[] {"Kas,0,"+lblTotal.getText(),"Stock,"+lblTotal.getText()+",0"};
        }
        else{
            perkiraan = new String[] {"Hutang,0,"+lblTotal.getText(),"Stock,"+lblTotal.getText()+",0"};
        }
        
        OCAMS.SQL.pencatatanJurnalTransaksi(lblTrans.getText(), "Setok Barang", perkiraan, OCAMS.userYangLogin.getKdUser());
        JOptionPane.showMessageDialog(this, "Berhasil Disimpan!");
        parent.updateTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(table.getRowCount() > 0){
            table.removeRow(GView.getSelectedRow());
        }
        updateTotal();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbNamaFocusLost
        lblSatuan.setText(OCAMS.SQL
            .executeGetScalar(
                "SELECT satuan from bahan where nama_bahan = '"+cb.getSelectedItem().toString()+"'"));
    }//GEN-LAST:event_cbNamaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cbHutang;
    private javax.swing.JRadioButton cbKas;
    private javax.swing.JComboBox<String> cbNama;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSatuan;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTrans;
    private javax.swing.JSpinner spJumlah;
    private javax.swing.JTextField txtHargaBeli;
    // End of variables declaration//GEN-END:variables
}
