package com.ocams.benyamin;

import com.ocams.OCAMS;
import com.ocams.abed.UAdmin;
import com.ocams.abed.UManager;
import java.security.SecureRandom;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ben
 */
public class FormDetailKasir extends javax.swing.JFrame {
    DefaultTableModel table;
    DefaultComboBoxModel<String> cbMenu;
    int maksDelete=-1;
    FormHeaderKasir parent;
    /**
     * Creates new form FormKasir
     */
    public void setParent(FormHeaderKasir parent){
        this.parent = parent;
    }
    
    public FormDetailKasir() {
        this.setUndecorated(true);
        this.setType(Type.UTILITY);
        initComponents();
        String kode = "";
        this.toFront();
        do {
            kode = randomID();
        } while (Integer.parseInt(OCAMS.SQL.executeGetScalar(
                "SELECT COUNT(*) FROM HEADER_JUAL WHERE ID_TRANS = '" + randomID() + "'")) > 0);
        start(kode);
    }
    
    public FormDetailKasir(String kode){
        this.setUndecorated(true);
        this.setType(Type.UTILITY);
        initComponents();
        start(kode);
        txtMejaNo.setText(OCAMS.SQL.executeGetScalar("SELECT meja from header_jual where id_trans = '"+kode+"'"));
        ArrayList<String[]> temp = OCAMS.SQL.executeQueryGetArray(
            "SELECT d.ID_MENU, m.nama_menu, h.harga_jual, d.jumlah, d.jumlah * h.harga_jual\n" +
            "FROM \n" +
            "    menu m, \n" +
            "    detail_jual d, \n" +
            "    (SELECT id_menu,harga_jual, berlaku FROM harga) h, \n" +
            "    (select id_menu, max(berlaku) as berlaku from harga group by id_menu) b\n" +
            "WHERE\n" +
            "    d.id_menu = m.id_menu and \n" +
            "    h.id_menu = m.id_menu and \n" +
            "    d.id_menu = m.id_menu and \n" +
            "    b.id_menu = m.id_menu and\n" +
            "    h.berlaku = b.berlaku and \n" +
            "    d.ID_Jual = '"+kode+"'");
        for(String[] d: temp){
            table.addRow(d);
        }
        updateTotal();
        lock();
    }
    
    private void lock(){
        maksDelete = table.getRowCount();
        // Disable Some Part of the Form
        btnClear.setEnabled(false); btnTransaksi.setText("Simpan Data"); txtMejaNo.setEnabled(false);
    }
    
    public void start(String kode){
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE); // Ini untuk supaya ga close EXIT
        lblTransaksi.setText(kode);
        lblUser.setText(OCAMS.userYangLogin.getNama());
        String judul[] = {"Kode Menu","Nama Menu","Harga","Jumlah","Total"};
        table = new DefaultTableModel(null, judul){
            // http://stackoverflow.com/questions/1990817/how-to-make-a-jtable-non-editable
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        String tanggal = new SimpleDateFormat("dd-mm-yyyy").format(new Date());
        lblTgl.setText(tanggal); 
        GView.setModel(table);
        ArrayList<String[]> data = OCAMS.SQL.executeQueryGetArray("SELECT nama_menu from menu");
        cbMenu = new DefaultComboBoxModel<>();
        cbMenuList.setModel(cbMenu);
        for(String[] d: data){
            cbMenu.addElement(d[0]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTgl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbMenuList = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GView = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        btnBayar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        spJumlah = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        btnTransaksi = new javax.swing.JButton();
        txtMejaNo = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTransaksi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Tanggal");

        lblTgl.setText("Tgl Jalan");

        jLabel3.setText("Menu");

        lblUser.setText("Nama User");

        jLabel5.setText("User");

        cbMenuList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTambah.setText("Tambah");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });

        GView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(GView);

        jLabel6.setText("Sub Total");

        lblSubTotal.setText("000000");

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        jLabel8.setText("Meja");

        spJumlah.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel10.setText("Jumlah");

        btnTransaksi.setText("Transaksi");
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
        });

        txtMejaNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMejaNoFocusLost(evt);
            }
        });

        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        jLabel2.setText("ID Trans");

        lblTransaksi.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbMenuList, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSubTotal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTransaksi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2)
                                .addComponent(lblTgl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtMejaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUser))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTransaksi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBayar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUser)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)
                        .addComponent(txtMejaNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTransaksi)
                        .addComponent(jLabel1)
                        .addComponent(lblTgl)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbMenuList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah)
                            .addComponent(spJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(btnHapus)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblSubTotal)
                    .addComponent(btnBayar)
                    .addComponent(btnTransaksi)
                    .addComponent(btnClear))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        String kode = OCAMS.SQL.executeQueryGetArray("SELECT id_menu FROM menu where nama_menu like '%" 
                + cbMenu.getSelectedItem().toString() + "%'").get(0)[0];
        int jumlah = Integer.parseInt(spJumlah.getValue().toString());
        int harga = Integer.parseInt(OCAMS.SQL.executeQueryGetArray("SELECT `harga_jual` FROM `harga` "
                + "where `id_menu` = '" + kode + "' "
                + "and `berlaku` = (select max(`berlaku`) from `harga` where `id_menu` = '" + kode + "')").get(0)[0]);
        int total = jumlah * harga;
        String data[] = {kode,cbMenu.getSelectedItem().toString(),String.valueOf(harga),
            String.valueOf(jumlah),String.valueOf(total)};
        boolean check = true;
        for (int i = 0; i < table.getRowCount(); i++) {
            if(table.getValueAt(i, 0).toString().trim().equals(kode)) {
                table.setValueAt(Integer.parseInt(table.getValueAt(i, 3).toString())+jumlah, i, 3);
                table.setValueAt(Integer.parseInt(table.getValueAt(i, 2).toString()) 
                        * Integer.parseInt(table.getValueAt(i, 3).toString()), i, 4);
                check = false;
            }
        }
        if(check || table.getRowCount() <=0) table.addRow(data);
        updateTotal();
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        if(table.getRowCount() > 0 ){
            if(GView.getSelectedRow() >= maksDelete){
                table.removeRow(GView.getSelectedRow());
            }
            else{
                JOptionPane.showMessageDialog(this, "Delete pada menu yang dipesan sebelumnya "
                        + "tidak diperbolehkan! Hubungi manager untuk instruksi lebih lanjut!"
                        , "STOP!", JOptionPane.WARNING_MESSAGE);
            }
        } 
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        while(table.getRowCount() > 0){
            table.removeRow(0);
        }
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        String waktu = String.format("%02d",LocalTime.now().getHour()) + String.format("%02d",LocalTime.now().getMinute());
        int cek = Integer.parseInt(OCAMS.SQL.executeGetScalar(
                "SELECT COUNT(*) FROM HEADER_JUAL WHERE MEJA = '"+txtMejaNo.getText()+"' AND STATUS = 0"));
        if(cek > 0 && txtMejaNo.isEnabled()) {
            JOptionPane.showMessageDialog(this, 
            "Peringatan! Meja yang anda inputkan masih ada orangnya!","STOP!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            OCAMS.SQL.executeNonQuery("INSERT INTO header_jual"
                    + "(ID_Trans,Tanggal,Jam,Operator,status,meja) "
                    + "VALUES('"+lblTransaksi.getText()+"','"+LocalDate.now()
                    +"','"+waktu+"','"+OCAMS.userYangLogin.getKdUser()+"',0,"+txtMejaNo.getText()+") "
                    + "on DUPLICATE KEY UPDATE ID_Trans = VALUES(ID_Trans),Tanggal = VALUES(Tanggal),"
                    + "Jam = VALUES(Jam),Operator= VALUES(Operator),status= VALUES(status),meja= VALUES(meja)");
            for (int i = 0; i < table.getRowCount(); i++) {
                String values = "'"+lblTransaksi.getText() + "','" + // Kode Trans
                        table.getValueAt(i, 0).toString() + "'," + // Kode Makanan
                        table.getValueAt(i, 3).toString();
                OCAMS.SQL.executeNonQuery("INSERT INTO detail_jual(ID_Jual,ID_Menu,Jumlah) VALUES("+values+")"
                        + " on  DUPLICATE KEY UPDATE"
                        + " ID_Jual = VALUES(ID_JUAL) , ID_MENU = VALUES(ID_MENU), JUMLAH = VALUES(JUMLAH)");
            }
            JOptionPane.showMessageDialog(this, "Transaksi Berhasil!");
            if(txtMejaNo.isEnabled() == false || OCAMS.userYangLogin instanceof UManager ||
                    OCAMS.userYangLogin instanceof UAdmin) lock();
        }
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void txtMejaNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMejaNoFocusLost
        int cek = Integer.parseInt(OCAMS.SQL.executeGetScalar(
                "SELECT COUNT(*) FROM HEADER_JUAL WHERE MEJA = '"+txtMejaNo.getText()+"' AND STATUS = 0"));
        if(cek > 0) JOptionPane.showMessageDialog(this, 
                "Peringatan! Meja yang anda inputkan masih ada orangnya!","STOP!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_txtMejaNoFocusLost

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        int bayar=0,cek=0;
        String text="";
        do {
            text = JOptionPane.showInputDialog(this, "Masukan Jumlah Pembayaran!");
            if(text != null) bayar = Integer.parseInt(text);
            cek++;
            if(cek > 1) JOptionPane.showMessageDialog(this, "Uang Kurang, Minta uang lagi ke pelanggan!");
        } while (bayar - Integer.parseInt(lblSubTotal.getText()) < 0 && text != null);
        if(text != null){
            JOptionPane.showMessageDialog(this, "Close Bill berhasil!\n\nKembali = " 
                    + String.valueOf(bayar - Integer.parseInt(lblSubTotal.getText())));
            OCAMS.SQL.executeNonQuery("UPDATE HEADER_JUAL SET status = 1 where id_trans = '"+lblTransaksi.getText()+"'");
        }
        //parent.updateTable();
    }//GEN-LAST:event_btnBayarActionPerformed
    
    public void lunas(){
        
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.updateTable();
    }//GEN-LAST:event_formWindowClosing
    
    public String randomID(){
        String temp = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890";
        String hasil = "";
        char charArray[] = temp.toCharArray();
        for (int i = 0; i < 10; i++) {
            Random random = new SecureRandom();
            hasil += String.valueOf(charArray[random.nextInt(charArray.length)]);
        }
        return hasil;
    }
    
    private void updateTotal(){
        int total = 0;
        if(table.getRowCount() > 0){
            for (int i = 0; i < table.getRowCount(); i++) {
                total += Integer.parseInt(table.getValueAt(i, 4).toString());
            }
        }
        lblSubTotal.setText(String.valueOf(total));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDetailKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDetailKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDetailKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDetailKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDetailKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GView;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JComboBox<String> cbMenuList;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTgl;
    private javax.swing.JLabel lblTransaksi;
    private javax.swing.JLabel lblUser;
    private javax.swing.JSpinner spJumlah;
    private javax.swing.JTextField txtMejaNo;
    // End of variables declaration//GEN-END:variables
}
